services:
    tig.blobuploader.controller.blobuploader:
        class: tig\blobuploader\controller\blobuploader
        arguments:
            - '@config'
            - '@user'
            - '@language'
            - '@request'
            # - '%core.root_path%'
            # - '%core.php_ext%'            

    tig.blobuploader.controller.acp:
        class: tig\blobuploader\controller\acp_controller
        arguments:
            - '@config'
            - '@config_text'
            - '@language'
            - '@log'
            - '@request'
            - '@template'
            - '@user'

    tig.blobuploader.listener:
        class: tig\blobuploader\event\main_listener
        arguments:
            - '@config'
            - '@config_text'        
            - '@language'
            - '@controller.helper'
            - '@template'
            - '%core.php_ext%'
            - '@request'
            
        tags:
            - { name: event.listener }
